site_name: WaterCS
site_author: 'Water-CS-Application'
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search
theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
  palette:
    - scheme: default
      primary: white # 上方的
      accent: cyan # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
nav:
  - "index.md"
  - 项目介绍:
      - HK:
          - CS@CUHK: "Program/HK/T1/CS@CUHK.md"
      - SG:
          - Mcomp@NUS: "Program/SG/T1/Mcomp@NUS.md"
          - AI@NTU: "Program/SG/T1/AI@NTU.md"
repo_url: https://github.com/Water-CS-Application/WaterCS
repo_name: WaterCS